AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - "db/schema.rb"
    - "node_modules/**/*"
    - 'vendor/**/*'
Rails:
  Enabled: true
Metrics/LineLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Rails/BulkChangeTable:
  Enabled: false
