language: ruby

services:
- postgresql

bundler_args: "--without development"

cache: bundler

before_script:
# - psql -U postgres -c 'create database travis_ci_test;'
# - cp config/database.yml.travis config/database.yml

script:
- bundle exec rubocop
# - env RAILS_ENV=test bin/rails db:migrate
# - bin/rails test

notifications:
  email: false
