language: ruby

services:
- postgresql

bundler_args: "--without development"

cache: bundler

before_script:
- psql -U postgres -c 'create database myapp_test;'

script:
- bundle exec rubocop
- env RAILS_ENV=test bin/rails db:migrate
- bin/rails test
- bundle exec brakeman

notifications:
  email: false
