language: ruby
services:
- postgresql
bundler_args: "--without development"
cache:
- bundler
env:
- DATABASE_URL=postgres://postgres@localhost/myapp_test
before_script:
- bin/rails db:create
- yarn install
script:
- bundle exec rubocop
- bin/rails test
- bundle exec brakeman
notifications:
  email: false
  slack:
    secure: GAuxrN7YchpxQaN50ykXUelWdQx3JoUGID7Ma5sPqLS88KLpaoAgLNvbo6AW9dtDMyujXz7fZxj7rPDo2Zx+RLqfx53W08hb042DJnh0HCGAnJEbR9isy6sTdVQQNxRuAI86CR5xHRSlRB1F7SiL+UB/cDpvhkRvjOAx8XOa8cvvLgDjyrARSX2iRtTvPHXKVpTGfLRf5WYNBM4UmpI+igCoH2FOjcPTAcaje7j8ubc28DIjmgPErme8nYpGxkVj1vzLQMcZUSnGd+7GKONs8oIfb43spHsA/tf8aLgd0htPbtS9Q1gq6rU9XvPqII2v006gS6bcwytF6lbCYOA8gMJYm1X0GWiufsqiCcLeyy1rZ/iQR21lKyhH1IEceUYKZHLL7deIUU+U90RV5oy2iHHf2ZMu73DBLwhiRbbi4Cr4c5RQGoRTAbgHiS0XDZhseRtiRLrcD9cO7EnhwpttY9CjZpTKrv7gSGo+4XWWvOH738HqtThwbEaSOi9JkAc9tjGhGFd7dm7URQkPjx2zkT+hUbtXrytCHD6a6Jg3l2LQwoMRc4IheFzLOoJJfKO+yO9TYlMmlgCSj1bDLvaRYeYvAsc8TwGQvt0JfJsJgOB4VE5IC5DNE2GaSobTFcaX81UxoZweZRnrgs1iol/y1qIteluSeeiCX5ETSYpelP8=
