version: "3"
services:
  db:
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data
  app: &app
    build: .
    volumes:
      - .:/usr/local/src
      - vendor_bundle:/usr/local/bundle
      - node_modules:/usr/local/src/node_modules
  web:
    <<: *app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
  deploy:
    image: hashicorp/terraform:light
    volumes:
      - .:/usr/local/src
    working_dir: /usr/local/src
volumes:
  vendor_bundle:
  node_modules:
  database:
